In [5]:
import pandas as pd 
import numpy as np 

In [3]:
df=pd.read_csv('insurance.csv')

In [10]:
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [7]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split

In [11]:
from sklearn.preprocessing import LabelEncoder
le_sex=LabelEncoder()
df['sex']=le_sex.fit_transform(df['sex'])
df["sex"].unique()

array([0, 1])

In [13]:
le_smoker=LabelEncoder()
df['smoker']=le_smoker.fit_transform(df['smoker'])
df["smoker"].unique()

array([1, 0])

In [15]:
le_region=LabelEncoder()
df['region']=le_region.fit_transform(df['region'])
df["region"].unique()

array([3, 2, 1, 0])

In [18]:
X=df.drop(columns='charges',axis=1)
y=df.charges
X_train, X_test, y_train, y_test = train_test_split( X, y, random_state=0)

In [19]:
model = GradientBoostingRegressor(random_state=0)

In [20]:
model.fit(X_train, y_train)

GradientBoostingRegressor(random_state=0)

In [21]:
yp=model.predict(X_test)

In [22]:
from sklearn.metrics import mean_squared_error

In [23]:
error=np.sqrt(mean_squared_error(y_test,yp))
error

4455.64387410101

In [30]:
t=np.array([[20,"male",27.90,2,"yes","southwest"]])
t

array([['20', 'male', '27.9', '2', 'yes', 'southwest']], dtype='<U32')

In [31]:
t[:,1]=le_sex.transform(t[:,1])
t[:,4]=le_smoker.transform(t[:,4])
t[:,5]=le_region.transform(t[:,5])
t=t.astype(float)
t

array([[20. ,  1. , 27.9,  2. ,  1. ,  3. ]])

In [33]:
import pickle

In [35]:
data={"model":model,"le_sex":le_sex,"le_smoker":le_smoker,"le_region":le_region}
with open ('steps.pkl','wb') as file:
    pickle.dump(data,file)

In [37]:
df['bmi'].unique()

array([27.9  , 33.77 , 33.   , 22.705, 28.88 , 25.74 , 33.44 , 27.74 ,
       29.83 , 25.84 , 26.22 , 26.29 , 34.4  , 39.82 , 42.13 , 24.6  ,
       30.78 , 23.845, 40.3  , 35.3  , 36.005, 32.4  , 34.1  , 31.92 ,
       28.025, 27.72 , 23.085, 32.775, 17.385, 36.3  , 35.6  , 26.315,
       28.6  , 28.31 , 20.425, 32.965, 20.8  , 36.67 , 39.9  , 26.6  ,
       36.63 , 21.78 , 30.8  , 37.05 , 37.3  , 38.665, 34.77 , 24.53 ,
       35.2  , 35.625, 33.63 , 28.   , 34.43 , 28.69 , 36.955, 31.825,
       31.68 , 22.88 , 37.335, 27.36 , 33.66 , 24.7  , 25.935, 22.42 ,
       28.9  , 39.1  , 36.19 , 23.98 , 24.75 , 28.5  , 28.1  , 32.01 ,
       27.4  , 34.01 , 29.59 , 35.53 , 39.805, 26.885, 38.285, 37.62 ,
       41.23 , 34.8  , 22.895, 31.16 , 27.2  , 26.98 , 39.49 , 24.795,
       31.3  , 38.28 , 19.95 , 19.3  , 31.6  , 25.46 , 30.115, 29.92 ,
       27.5  , 28.4  , 30.875, 27.94 , 35.09 , 29.7  , 35.72 , 32.205,
       28.595, 49.06 , 27.17 , 23.37 , 37.1  , 23.75 , 28.975, 31.35 ,
      